package com.example.ramki.listy.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.ramki.listy.model.TodoEntries;

import com.example.ramki.listy.model.TodoEntriesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoEntriesDaoConfig;

    private final TodoEntriesDao todoEntriesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoEntriesDaoConfig = daoConfigMap.get(TodoEntriesDao.class).clone();
        todoEntriesDaoConfig.initIdentityScope(type);

        todoEntriesDao = new TodoEntriesDao(todoEntriesDaoConfig, this);

        registerDao(TodoEntries.class, todoEntriesDao);
    }
    
    public void clear() {
        todoEntriesDaoConfig.getIdentityScope().clear();
    }

    public TodoEntriesDao getTodoEntriesDao() {
        return todoEntriesDao;
    }

}
