package com.example.ramki.listy.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.support.annotation.NonNull;

/**
 * Entity mapped to table TODO_ENTRY.
 */
public class TodoEntry extends TodoEntryComparable  {

    private Long id;
    /** Not-null value. */
    private String title;
    private String notes;
    private boolean deleted;
    /** Not-null value. */
    private java.util.Date created_on;
    private java.util.Date due;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TodoEntry() {
    }

    public TodoEntry(Long id) {
        this.id = id;
    }

    public TodoEntry(Long id, String title, String notes, boolean deleted, java.util.Date created_on, java.util.Date due) {
        this.id = id;
        this.title = title;
        this.notes = notes;
        this.deleted = deleted;
        this.created_on = created_on;
        this.due = due;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    /** Not-null value. */
    public java.util.Date getCreated_on() {
        return created_on;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated_on(java.util.Date created_on) {
        this.created_on = created_on;
    }

    public java.util.Date getDue() {
        return due;
    }

    public void setDue(java.util.Date due) {
        this.due = due;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public int compareTo(@NonNull TodoEntryComparable another) {
        TodoEntry anotherTodo = (TodoEntry) another;
        if (this.due == null) return 1;
        if (anotherTodo.due == null) return -1;
        return this.due.compareTo(anotherTodo.due);
    }
    // KEEP METHODS END

}
