package com.example.ramki.listy.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TODO_ENTRIES.
 */
public class TodoEntries {

    private Long id;
    private String title;
    private String notes;
    private Boolean deleted;
    private java.util.Date created_on;
    private java.util.Date due;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TodoEntries() {
    }

    public TodoEntries(Long id) {
        this.id = id;
    }

    public TodoEntries(Long id, String title, String notes, Boolean deleted, java.util.Date created_on, java.util.Date due) {
        this.id = id;
        this.title = title;
        this.notes = notes;
        this.deleted = deleted;
        this.created_on = created_on;
        this.due = due;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public java.util.Date getCreated_on() {
        return created_on;
    }

    public void setCreated_on(java.util.Date created_on) {
        this.created_on = created_on;
    }

    public java.util.Date getDue() {
        return due;
    }

    public void setDue(java.util.Date due) {
        this.due = due;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
