package com.example.ramki.listy.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.ramki.listy.model.TodoEntry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TODO_ENTRY.
*/
public class TodoEntryDao extends AbstractDao<TodoEntry, Long> {

    public static final String TABLENAME = "TODO_ENTRY";

    /**
     * Properties of entity TodoEntry.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Notes = new Property(2, String.class, "notes", false, "NOTES");
        public final static Property Deleted = new Property(3, boolean.class, "deleted", false, "DELETED");
        public final static Property Created_on = new Property(4, java.util.Date.class, "created_on", false, "CREATED_ON");
        public final static Property Due = new Property(5, java.util.Date.class, "due", false, "DUE");
    };


    public TodoEntryDao(DaoConfig config) {
        super(config);
    }
    
    public TodoEntryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TODO_ENTRY' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'TITLE' TEXT NOT NULL ," + // 1: title
                "'NOTES' TEXT," + // 2: notes
                "'DELETED' INTEGER NOT NULL ," + // 3: deleted
                "'CREATED_ON' INTEGER NOT NULL ," + // 4: created_on
                "'DUE' INTEGER);"); // 5: due
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TODO_ENTRY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TodoEntry entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String notes = entity.getNotes();
        if (notes != null) {
            stmt.bindString(3, notes);
        }
        stmt.bindLong(4, entity.getDeleted() ? 1l: 0l);
        stmt.bindLong(5, entity.getCreated_on().getTime());
 
        java.util.Date due = entity.getDue();
        if (due != null) {
            stmt.bindLong(6, due.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TodoEntry readEntity(Cursor cursor, int offset) {
        TodoEntry entity = new TodoEntry( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // notes
            cursor.getShort(offset + 3) != 0, // deleted
            new java.util.Date(cursor.getLong(offset + 4)), // created_on
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)) // due
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TodoEntry entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setNotes(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeleted(cursor.getShort(offset + 3) != 0);
        entity.setCreated_on(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setDue(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TodoEntry entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TodoEntry entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
